### ISSUE TITLE
Problems when starting two jobs on same node

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#135]
I have made a release 2.1.17 of CMFEditions. Now node 2 has a wrong download of this package. See this output of console 2, the first job where it fails: http://jenkins.plone.org/job/plone-5.0-python-2.7/3386/console

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/py_compile.py", line 181, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/py_compile.py", line 173, in main
    compile(filename, doraise=True)
  File "/usr/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory: '/home/jenkins/.buildout/eggs/Products.CMFEditions-2.2.17-py2.7.egg/Products/CMFEditions/ZVCStorageTool.py'
While:
  Installing instance.
  Getting distribution for 'Products.CMFEditions==2.2.17'.
```

So it is expecting a file and not finding it. Strange.  The package works fine locally.

But a second job was started around that same time.
http://jenkins.plone.org/job/plone-5.0-python-2.7/3387/console

```
While:
  Installing instance.
  Getting distribution for 'Products.CMFEditions==2.2.17'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/home/jenkins/.buildout/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 113, in install
    installed.extend(self.install_scripts())
  File "/home/jenkins/.buildout/eggs/plone.recipe.zope2instance-4.2.18-py2.7.egg/plone/recipe/zope2instance/__init__.py", line 617, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "/home/jenkins/.buildout/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/egg/egg.py", line 101, in working_set
    **kw)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 883, in install
    return installer.install(specs, working_set)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 714, in install
    for_buildout_run=for_buildout_run):
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 552, in _get_dist
    dist.location, ws, self._dest, dist)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/easy_install.py", line 403, in _call_easy_install
    shutil.rmtree(newloc)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/jenkins/.buildout/eggs/Products.CMFEditions-2.2.17-py2.7.egg/Products/CMFEditions'
```

So I am guessing the first job is busy unpacking the CMFEditions package and then the second job is about to do the same thing and they clash and crash.

I have seen similar problems before. Usually either a next run is fine again, or I make a new release.  In this case I indeed have made a second CMFEditions release, 2.1.18, so the test failures should be fixed in a while.

But is the general problem somehow solvable?  Maybe something like: if one job is still in the buildout phase, do not accept another job.  Or a new job checks if a buildout is still running and in that case waits a few minutes.

Buildout or an encompassing script could probably create a file `~/BUILDOUT_RUNNING` with a process id in it.  You could then check for existence of this file, and if the process id in it is still running and if it is not older than five minutes.  Possibly done as a buildout extension.

Just some thoughts.

**Comment by gforcada** [comment]
We could get rid of the ``.buildout`` folder and instead have a per job one... then we would only need to make sure that the same job does not run twice on the same node and that would be it...

The only problem would be disk size, but I'm not so sure if that's much of an issue actually...

**Comment by tisto** [comment]
We could get rid of the local buildout cache and use a pypi local pypi
mirror instead.

**Comment by mauritsvanrees** [comment]
We can keep sharing the download-cache.

**Comment by mauritsvanrees** [comment]
I am seeing this again, and have seen it multiple times in between. Now it is a plone.app.i18n package that gets broken because two jobs are installing it at the same time.

There is a `~/.buildout/default.cfg` on all nodes I guess? And it has an `eggs-directory` and `download-cache` setting, right? I think we can keep the `download-cache` and should remove the `eggs-directory` setting. Then we only download each distribution once from PyPI, but have an egg per job, so the above can't happen.

Alternatively, we could add `eggs-directory = eggs` in `jenkins.cfg` in the coredev buildouts. That should solve it too.

**Comment by gforcada** [comment]
@mauritsvanrees yes you are right the ``default.cfg`` is there with

```
eggs-directory = /home/jenkins/.buildout/eggs
download-directory = /home/jenkins/.buildout/downloads
```

Removing the first line then it would mean that nearly every job will have ~1Gb of data, which given our  hard disk shortcomings some weeks ago does not look like a realistic option.

@svx can we get more hard disk on the nodes?
