### ISSUE TITLE
Pull Request Failure on Jenkins: AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#216]
Testing my pull request fails:

http://jenkins.plone.org/view/All/job/pull-request-5.1/730/console

with:

```
$ /home/jenkins/shiningpanda/jobs/b0ec4c2e/virtualenvs/0dd3bfc1/bin/python /tmp/shiningpanda6574206922045914381.py
Traceback (most recent call last):
  File "/tmp/shiningpanda6574206922045914381.py", line 52, in <module>
    org, plone_repo, pr_number = re.search(PR_RE, pr).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
Build step 'Virtualenv Builder' marked build as failure
Xvfb stopping
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Robot results publisher started...
-Parsing output xml:
Failed!
/home/jenkins/workspace/pull-request-5.1/parts/test does not exist.
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:483)
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:460)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:72)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:54)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2760)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to Node1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at hudson.FilePath.act(FilePath.java:986)
		at hudson.FilePath.act(FilePath.java:975)
		at hudson.plugins.robot.RobotParser.parse(RobotParser.java:49)
		at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:217)
		at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:239)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1749)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:421)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Email was triggered for: Always
Sending email for trigger: Always
Sending email to: tisto@plone.org
Finished: FAILURE
```

@gforcada any idea?

**Comment by gforcada** [comment]
@tisto yes, because it is not a pull request, but an issue link: http://jenkins.plone.org/view/All/job/pull-request-5.1/730/parameters/
