### ISSUE TITLE
Add pull-request job for 5.2 on py3.8 to mr.roboto

### ISSUE THREAD

**Issue by pbauer** [plone/jenkins.plone.org#269]
Also all the Py3.8 jobs for Plone 5.2 seem broken. 
Maybe because of outdated bytecode (pyc-files):

```
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/cp38/plone.app.portlets-4.4.4-py3.8.egg/plone/app/portlets/tests/test_review_portlet.py", line 4, in <module>
    from Products.CMFCore.utils import getToolByName
  File "/home/jenkins/.buildout/eggs/cp38/Products.CMFCore-2.4.2-py3.8.egg/Products/CMFCore/__init__.py", line 24, in <module>
    from . import ActionInformation
  File "/home/jenkins/.buildout/eggs/cp38/Products.CMFCore-2.4.2-py3.8.egg/Products/CMFCore/ActionInformation.py", line 33, in <module>
    from .Expression import Expression
  File "/home/jenkins/.buildout/eggs/cp38/Products.CMFCore-2.4.2-py3.8.egg/Products/CMFCore/Expression.py", line 29, in <module>
    from .interfaces import IMembershipTool
  File "/home/jenkins/.buildout/eggs/cp38/Products.CMFCore-2.4.2-py3.8.egg/Products/CMFCore/interfaces/__init__.py", line 16, in <module>
    from ._content import *  # noqa
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 911, in get_code
  File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode
EOFError: marshal data too short
```

**Comment by gforcada** [comment]
I will try to have a look at night.

**Comment by mauritsvanrees** [comment]
jobs for 5.2 Python 3.8 run fine currently.
